name: Release Workflow

on:
  push:
    # Sequence of patterns matched against release branch
    branches: 'release/[12].[0-9]+.[0-9]+'
    paths: 'package.json'

jobs:
  job_id_1: # Build/testing job
    name: ReleaseJob-Build_on_GH
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps: #Steps for running build
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use NODE.js 
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: NPM CI and Build
        run: |
         git branch
         npm ci 
         npm run build
        env:
          CI: true

  job_id_2: # Release on github job
   needs: job_id_1
   name: ReleaseJob-Release_on_GH
   runs-on: ubuntu-latest
   steps:
     - name: Set ENV variable
       run: echo "::set-env name=GH_BRANCH::${GITHUB_REF##*/}" # Setting correct tagname
     - name: Create-Release-GH
       id: create_release_GH
       uses: actions/create-release@v1
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
       with:
        tag_name: ${{ env.GH_BRANCH }} # Using correct name for each tag
        release_name: ${{ env.GH_BRANCH }}
        draft: false
        prerelease: false
