name: Release Workflow

on:
  push:
    # Sequence of patterns matched against release branch
#     branches: 'release/[12].[0-9]+.[0-9]+'

jobs:
  job_id_1: # Build/testing job
    name: ReleaseJob-Build_on_GH
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # node-version: [10.x, 12.x]
        node-version: [10.x]

    steps: #Steps for running build
      - name: Checkout code
        uses: actions/checkout@master
      - name: Use NODE.js 
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: NPM CI and Build
        run: |
  #        npm ci 
  #        npm run build
        env:
          CI: true

  job_id_2: # Release on github job
   needs: job_id_1
   name: ReleaseJob-Release_on_GH
   runs-on: ubuntu-latest
   steps:
     - name: env variable
       id: env-var
       env:
          GH_BRANCH: ${GITHUB_REF}
       run: |
          GH_BRANCH=${GITHUB_REF##*/}
          echo $GH_BRANCH
          echo ${{ env.GH_BRANCH}}
     - run: echo "::set-env name=DAY_OF_WEEK::$( date +%a )"
     - run: echo "Somebody has a case of the mondays!"
       if: env.DAY_OF_WEEK == 'Mon'
     - run: echo "This runs every day..
     - name: Create-Release-GH
       id: create_release_GH
       uses: actions/create-release@v1
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
         GH_BRANCH: test
       with:
        tag_name: ${{ steps.env-var.env.GH_BRANCH}}
        release_name: ${{ steps.env-var.env.GH_BRANCH}}
        draft: false
        prerelease: false
