name: Pre-release published

on:
  push:
    # Sequence of patterns matched against pre-release branch e.g 1.0.0-1
    branches: 'release/[12].[0-9]+.[0-9]+-[0-9]+'

jobs:
  job_id_1: # Build/testing job
    name: Build on GH
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps: #Steps for running build
      - name: Checkout Github branch
        uses: actions/checkout@v2
      - name: Setup Node 
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: NPM CI and Build
        run: |
         git branch
         npm ci 
         npm run build
        env:
          CI: true

  job_id_2: # Pre-release on github job
   needs: job_id_1
   name: pre-release on GH
   runs-on: ubuntu-latest
   steps:
     - name: Set ENV variable
       run: echo "::set-env name=GH_BRANCH::${GITHUB_REF##*/}" # Setting correct tagname
     - name: Create-Release-GH
       id: create_release_GH
       uses: actions/create-release@v1
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
       with:
        tag_name: ${{ env.GH_BRANCH }} # Using correct name for each tag
        release_name: ${{ env.GH_BRANCH }}
        draft: false
        prerelease: true
