name: Release Workflow

on:
  push:
    # Sequence of patterns matched against refs/tags
    branches: 'release/**'

jobs:
  job_id_1:
    name: Release Job 1
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
      - name: Checkout master code
        uses: actions/checkout@master
      - name: Use NODE.js 
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: NPM CI and Build
        run: |
          npm ci
          npm run build
        env:
          CI: true

  job_id_2:
   name: release job 2
   runs-on: ubuntu-latest
   steps:
     - name: Create Release
       id: create_release
       uses: actions/create-release@v1
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
       with:
        tag_name: ${{ github.ref }}
        release_name: Version ${{ github.ref }}
        draft: false
        prerelease: false
