name: Release Workflow

on:
  push:
    # Sequence of patterns matched against release branch
    branches: 'release/[12].[0-9]+.[0-9]+'

jobs:
  job_id_1: # Build/testing job
    env: 
     GH_BRANCH: ${{ GITHUB_REF }}
    name: ReleaseJob-Build_on_GH
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps: #Steps for running build
      - name: Run a multi-line script
        run: |
          echo GH_BRANCH=${ GH_BRANCH##*/ }
          echo ${{ github.ref }}
          echo ${{ GH_BRANCH }}
          echo ${{ github.actor}}
      - name: Checkout master code
        uses: actions/checkout@master
      - name: Use NODE.js 
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: NPM CI and Build
        run: |
          npm ci 
          npm run build
        env:
          CI: true

  job_id_2: # Release on github job
   needs: job_id_1
   env: 
     GH_BRANCH: ${{ GITHUB_REF }}
   name: ReleaseJob-Release_on_GH
   runs-on: ubuntu-latest
   steps:
     - name: Add ENV var
       run: GH_BRANCH=${ GH_BRANCH##*/ }
     - name: Create Release GH
       id: create_release_GH
       uses: actions/create-release@v1
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
       with:
        tag_name: ${{ GH_BRANCH }}
        release_name: Version ${{ github.ref }}
        draft: false
        prerelease: false
